POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "igor.bb00@gmail.com",
  "password": "lkalala"
}


###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "igor.bb00@gmail.com",
  "password": "lkalala"
}

###

GET http://127.0.0.1:8000/portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZThjMjMyZS01YjY3LTQ3MGItODVmMS03YTlkMzk5OWUzODciLCJleHAiOjE3NjI2MTMzNDgsInR5cGUiOiJjb25maXJtYXRpb24ifQ.T9hHha3XtGSa8nO0FgKRz36m_Siupp1_WpqPXKMK4u0

###



POST http://127.0.0.1:8000/portfolios/buy?coin=bitcoin&quantity=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDM1NDgsInR5cGUiOiJjb25maXJtYXRpb24ifQ.pv-_6nmjX5UJ00h20T-sXNdvpy6AUdwmnTpXiWHWLX0


###


POST http://127.0.0.1:8000/portfolios/sell?coin=bitcoin&quantity=all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDM1NDgsInR5cGUiOiJjb25maXJtYXRpb24ifQ.pv-_6nmjX5UJ00h20T-sXNdvpy6AUdwmnTpXiWHWLX0


###

POST http://127.0.0.1:8000/portfolios/deposit?quantity=900000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDc1ODYsInR5cGUiOiJjb25maXJtYXRpb24ifQ.q05isFZvAzTH39v58dSfWxmt8yVbgYjd9AQptMkYkvk


###

POST http://127.0.0.1:8000/portfolios/withdraw?quantity=all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDc1ODYsInR5cGUiOiJjb25maXJtYXRpb24ifQ.q05isFZvAzTH39v58dSfWxmt8yVbgYjd9AQptMkYkvk


###

GET http://127.0.0.1:8000/portfolios/p_and_l_coin?coin=tether
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDY4ODMsInR5cGUiOiJjb25maXJtYXRpb24ifQ.UVbAhumllu0UwZ7HsG_hiPN5Xz6BKnYrKPVw41j4dOU

