POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "igor.bb00@gmail.com",
  "password": "lkalala"
}


###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "igor.bb00@gmail.com",
  "password": "lkalala"
}

###

GET http://127.0.0.1:8000/portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NTM3OTRkZC1kZGU1LTRmMjItYTcwNS0xMjdiNjE3MGQ4ZmUiLCJleHAiOjE3NjI3MTc1NjUsInR5cGUiOiJjb25maXJtYXRpb24ifQ.HUZ0PTbIVWza0s0Pw2HmoZDxpI-CjFB7pgabSD42nOg

###



POST http://127.0.0.1:8000/portfolios/buy?coin=bitcoin&quantity=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjI5NzczMzAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.SVknXRdk-q79fZq_gpjU_OECx2TV3TrjqVPvcNdTdvw


###


POST http://127.0.0.1:8000/portfolios/sell?coin=solana&quantity=140
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYmRkNmZmZi01OWJjLTRkMjEtYWRkNS1jOWU3NGQ0ZTU0OWEiLCJleHAiOjE3NjI4OTQzNzYsInR5cGUiOiJjb25maXJtYXRpb24ifQ.nDifuB9H6gQMV14S5UpIWQtmhuMQ4ekRTPdbCNNj6b4


###

POST http://127.0.0.1:8000/portfolios/deposit?quantity=9000000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjI5NzczMzAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.SVknXRdk-q79fZq_gpjU_OECx2TV3TrjqVPvcNdTdvw


###

POST http://127.0.0.1:8000/portfolios/withdraw?quantity=all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDc1ODYsInR5cGUiOiJjb25maXJtYXRpb24ifQ.q05isFZvAzTH39v58dSfWxmt8yVbgYjd9AQptMkYkvk


###

GET http://127.0.0.1:8000/portfolios/p_and_l_coin?coin=tether
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDY4ODMsInR5cGUiOiJjb25maXJtYXRpb24ifQ.UVbAhumllu0UwZ7HsG_hiPN5Xz6BKnYrKPVw41j4dOU


###

GET http://127.0.0.1:8000/crypto-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZThjMjMyZS01YjY3LTQ3MGItODVmMS03YTlkMzk5OWUzODciLCJleHAiOjE3NjI2MzU1NTUsInR5cGUiOiJjb25maXJtYXRpb24ifQ.-ch3RQi11idAgNlsDwl03H22EON7wxHGroA7oyA8G1M



###

GET http://127.0.0.1:8000/crypto-data/val?days=100&mode=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjI5NzY3MjAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.hIijDdrIvqLL8P1OOaHrV0EllU6ej2yNTjnflSOFHo8


###

GET http://127.0.0.1:8000/crypto-data/p_n_l_perc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjI5NTAwMzcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.0ryjMMg94zRpiGxdUZjIeCxTtQCK22AzsVBEe3ud_rI

###

GET http://127.0.0.1:8000/transactions/p_n_l
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjMwMjMyMzAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.u4syXeP2bNjygFbQ65MlP5zkKF01q_2ls83ClmO_ebI

###
