POST http://127.0.0.1:8000/users/register
Content-Type: application/json

{
  "email": "igor.bb00@gmail.com",
  "password": "lkalala"
}


###

POST http://127.0.0.1:8000/users/login
Content-Type: application/json

{
  "email": "igor.bb00@gmail.com",
  "password": "lkalala"
}

###

GET http://127.0.0.1:8000/portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5Mjc5NzEsInR5cGUiOiJjb25maXJtYXRpb24ifQ.4uJ2W1HmDJg7shjpi2Q0zpWD9K3AVYtiOD3pzB6ZgNQ

###



POST http://127.0.0.1:8000/portfolios/buy?coin=solana&quantity=1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MjQwMTcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.mbaqUnLKlIwp9o6kDYokpiyNmDVEi4EQrjxblUFusZs


###


POST http://127.0.0.1:8000/portfolios/sell?coin=solana&quantity=140
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYmRkNmZmZi01OWJjLTRkMjEtYWRkNS1jOWU3NGQ0ZTU0OWEiLCJleHAiOjE3NjI4OTQzNzYsInR5cGUiOiJjb25maXJtYXRpb24ifQ.nDifuB9H6gQMV14S5UpIWQtmhuMQ4ekRTPdbCNNj6b4


###

POST http://127.0.0.1:8000/portfolios/deposit?quantity=9000000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MTc3MTksInR5cGUiOiJjb25maXJtYXRpb24ifQ.LjKW4B72GYyRi5qxl2lRk36MWwNpLxbcqbL_Ay_U_lI


###

POST http://127.0.0.1:8000/portfolios/withdraw?quantity=all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OWI0MzFhMC04YjU3LTRkM2UtYmYyOS03YTA4YjA1OWUzNWYiLCJleHAiOjE3NjI2MDc1ODYsInR5cGUiOiJjb25maXJtYXRpb24ifQ.q05isFZvAzTH39v58dSfWxmt8yVbgYjd9AQptMkYkvk


###

GET http://127.0.0.1:8000/portfolios/p_and_l_coin?coin=bitcoin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MTc3MTksInR5cGUiOiJjb25maXJtYXRpb24ifQ.LjKW4B72GYyRi5qxl2lRk36MWwNpLxbcqbL_Ay_U_lI


###

GET 127.0.0.1:8000/transactions/p_n_l
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MjY3MzAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.Ezz8uIecqqFDIl6dRAmcxfHI0x1mz8QuP7iVBvWapYw

###


GET http://127.0.0.1:8000/transactions/val?days=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MjE1MTIsInR5cGUiOiJjb25maXJtYXRpb24ifQ.gWd6qBSoIoIilskE-yWlq1u9Wd_vvODZgLSqgnGcEAc


###

GET 127.0.0.1:8000/transactions/sep-coins?days=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MjQyMzksInR5cGUiOiJjb25maXJtYXRpb24ifQ.pznvPcuFOhjxKZEHQMUR8s4HiX2d4JQInM6eP1joGAk

###

GET 127.0.0.1:8000/transactions/p_n_l_perc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWM3ODg5Yi05ZGE1LTQzMWEtYTdmZS1mYzI5NWM0ZmJjMmYiLCJleHAiOjE3NjM5MjYyNDcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.0RMTNNjUiFS-tXLsHOyyOx4EWf6sEerRMNOJD2B7V-4

###


PUT http://127.0.0.1:8000/trade_requests/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjMyMzQ2NjAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.zogqGpuTnELhdsHDXF4pEe3DOfjRI6G83IiFAVonuQQ
Content-Type: application/json

{
  "accept": true,
  "request_id": "ec9cb598-f8f8-42c6-b29c-749145f47532"
}


###

GET http://127.0.0.1:8000/trade_requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOGFhYTdhOC1hZmRmLTQxMTItOTlkYi0wMTVkYWU0ZmY0YjUiLCJleHAiOjE3NjMyMzQ2NjAsInR5cGUiOiJjb25maXJtYXRpb24ifQ.zogqGpuTnELhdsHDXF4pEe3DOfjRI6G83IiFAVonuQQ



