# Test your FastAPI endpoints

POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "igora11111@gmail.com",
  "password": "lkalala"
}


###

GET http://127.0.0.1:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NmZmOTRhMy0wNDhiLTQ4NmYtODA4MS0zYmQ2MTUyMjQ3NjAiLCJleHAiOjE3NjIzNDgwMDksInR5cGUiOiJjb25maXJtYXRpb24ifQ.YXpLMovl2kcKlk4IsTaUQwNE174EDPftzxlC4IFrP2g

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "igora11111@gmail.com",
  "password": "lkalala"
}


###

GET http://127.0.0.1:8000/portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NmZmOTRhMy0wNDhiLTQ4NmYtODA4MS0zYmQ2MTUyMjQ3NjAiLCJleHAiOjE3NjIzNDkyMTcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.B1h4DqT1niWCpc9pWLFUV5Zgm3Cc1l-o9HnRw6DVnm4