# Test your FastAPI endpoints

POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "igora11111@gmail.com",
  "password": "lkalala"
}


###

GET http://127.0.0.1:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YzUwZmFhMy03ZmI4LTQ2ZGEtYTg4Ni03OTRlNzZiMTY0Y2MiLCJleHAiOjE3NjI0MjYyMDUsInR5cGUiOiJjb25maXJtYXRpb24ifQ.JvTGyFZ_SK-I9kMgUJk8WYimLxsjHuWv0OcZPe7VUwE

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "igora11111@gmail.com",
  "password": "lkalala"
}


###

GET http://127.0.0.1:8000/portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NGE0ZTNjMS03YmFiLTRmMmEtOTY3OS1hYzhhMDNjMGVlZTciLCJleHAiOjE3NjI1NDc2ODcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.Q8NWv4dXM6XDXe0hTov52Rli9mwkZGUcFt4zM26PJg4

###



POST http://127.0.0.1:8000/portfolios/buy?coin=bitcoin&quantity=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NGE0ZTNjMS03YmFiLTRmMmEtOTY3OS1hYzhhMDNjMGVlZTciLCJleHAiOjE3NjI1NDc2ODcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.Q8NWv4dXM6XDXe0hTov52Rli9mwkZGUcFt4zM26PJg4


###


POST http://127.0.0.1:8000/portfolios/sell?coin=bitcoin&quantity=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZGE0ZTdjYS0xMjVhLTQyZDUtODkwNi1lZTE5NmQzZWYzOWIiLCJleHAiOjE3NjI1NDI4ODksInR5cGUiOiJjb25maXJtYXRpb24ifQ.VOu3FFuGbereSlUT9Wf15Z2n5149Jh9jihaMknw7Yxg


###

POST http://127.0.0.1:8000/portfolios/deposit?quantity=9000000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NGE0ZTNjMS03YmFiLTRmMmEtOTY3OS1hYzhhMDNjMGVlZTciLCJleHAiOjE3NjI1NDc2ODcsInR5cGUiOiJjb25maXJtYXRpb24ifQ.Q8NWv4dXM6XDXe0hTov52Rli9mwkZGUcFt4zM26PJg4